# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e96dd7d4d8362d42d9056013c1b9dac65739f5b4b25d1e4ee6a39bb77a02e96aabd0458f26344030b3e8a77755aaa51e49e141694c15e36ba709136f567ff2aa

test:
  secret_key_base: e4093eccde582159beac37d4fc05f919d2a60efd3945a6ffd320be2e565747f605159d4b4a00dd03ec71ada64ba07dac43f9131e0106ab8da793dcba2d15ab8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
